### PR TITLE
Add basic "snapshot" test

### PR DESCRIPTION
**Pull request by joeykmh**
Hi there, I made a first basic tape test as you described in https://github.com/juliuste/westminster-svg/issues/1. If this is what you're looking for, I'd be happy to write a few more general test cases (also for westminster)!

### CODE REVIEW

**Comment by juliuste** [comment]
Looks nice! As you mentioned, having another test case for more than just 2 seats would be nice, if you want to do that 👍 (Even if not, thank you! 😄)

**Comment by juliuste** [comment]
Should I merge this or do you want to add something? (Like another test case)

**Comment by joeykmh** [comment]
Just wanted to make sure it was what you were looking for before investing too much time :) I'll add a few more test cases and re-commit.

**Comment by derhuerst** [comment]
Maybe put the snapshot in a file, e.g. `test/2-parties-no-seat-count.json`? Would increase the test readability a lot.

**Comment by juliuste** [comment]
#6 (just for the reference in the issue 😄)

**Comment by joeykmh** [comment]
Alright, I just added a few more cases, including your demo data from the readme. Please merge if it looks good to you!

@derhuerst thanks for the suggestion - I moved the test data into a separate directory, but JSON (especially many `undefined` properties) did not play nice with tape's `deepEqual()`. So I'm just importing JS objects. More readable?

**Comment by juliuste** [comment]
Thank you very much!

**Pull request merged**
